### ISSUE TITLE
Add an optional dependency on python-fastpbkdf2

### ISSUE THREAD

**Issue by Ayrx** [pallets/werkzeug#1022]
Hello,

Would werkzeug accept a patch that adds an optional dependecy on [python-fastpbkdf2](https://github.com/Ayrx/python-fastpbkdf2) preferring it over the stdlib and the pure Python implementation if installed? python-fastpbkdf2 is a `hashlib.pbkdf2_hmac` API compatible implementation that's much faster than the stdlib implementation. This would result in a win for security because users can tune the PBKDF2 parameters much higher for the same hardware.

Disclaimer: I am the author and maintainer of python-fastpbkdf2.

**Comment by RonnyPfannschmidt** [comment]
sounds like a good idea, maybe also for itsdangerous?

in general for stuff like that, the faster the server can run it, the more secure it can be made due to iteration number

@untitaker oppinion?

**Comment by untitaker** [comment]
I am vary of having unaudited or just not widely used crypto libraries implicitly endorsed by Werkzeug. Cryptography.io is the library I would recommend for whatever usecases it can cover (and it does seem that it has a PBKDF2 API).

**Comment by Ayrx** [comment]
FWIW, passlib will have an optional dependecy on [this](https://bitbucket.org/ecollins/passlib/issues/67/add-an-optional-dependency-on-python) in the next version. 

The pyca/cryptography implementation is slightly slower than the stdlib the last time I benchmarked it(which makes sense because they both bind OpenSSL and CFFI takes a _slight_ performance hit on CPython).

**Comment by untitaker** [comment]
I'm not fond of passlib. Its docs *recommend* sha256 as a password hashing algorithm which is completely misleading. If you have a UI like that, it doesn't matter anymore whether your PBKDF2 is slightly faster.

**Comment by davidism** [comment]
Against this, to the point I'd rather deprecate the built in password functions and recommend something else. They're there for convenience, not for speed or extensibility. I don't recall passlib recommending bare sha256 as a hash, but haven't looked at the docs in a while.

**Comment by RonnyPfannschmidt** [comment]
@untitaker makes important points
@Ayrx from the audit standpoint, it would be much better if your speedup was coming in via cryptography and was audited than a random small just your own package

im not claiming that anything with your library is wrong,
but we have to take into account that none of us could confidently audit it
in the detail that would do it justice

**Comment by jeffwidman** [comment]
I'm in favor of adding a note to the docs recommending that users use this in their Werkzeug projects. 

However, I'm leery of actually doing this in code because what happens if the stdlib and this external library start to drift apart on compatibility? Over in Flask, the optional dependency on `simplejson` vs stdlib `json` has resulted in extra cornercases and occasionally more difficult debugging when someone didn't realize a non-stdlib version was being pulled in under the covers.

**Comment by untitaker** [comment]
Jeff, could you give arguments for recommending this in the docs? I have serious concerns about endorsing an unknown library if its use is critical to security.

**Comment by Ayrx** [comment]
Oh no, don't deprecate the ones built into werkzeug. Their helpful. It's
alright if the idea of integrating python-fastpbkdf2 isn't accepted but the
ones you already got are still good.

**Comment by jeffwidman** [comment]
> I have serious concerns about endorsing an unknown library if its use is critical to security.

You're right (as usual). I wasn't thinking of the security problems; I was more thinking about all the edge cases, potential problems and confusing debugging that's introduced when an optional dependency is added that overrules built-in behavior. Very different (in my mind) than adding an optional dependency that adds additional functionality.

**Comment by davidism** [comment]
We're wary of adding *any* optional dependency, whether it effects security or not, since it adds a lot of maintenance costs.  Additionally, we don't add recommendations for libraries all over the docs since those would always be incomplete and ever-changing.

I don't want this to come off as us passing judgement on you or your work.  I'm sure that if people are concerned with pbkdf2 speed in their application they'll come across yours and other libraries naturally
