### ISSUE TITLE
large file uploads eating up memory

### ISSUE THREAD

**Issue by cecemel** [pallets/werkzeug#1041]
Hi, 

**PLEASE NOTE**: this is a repost from [flask issue 2068](https://github.com/pallets/flask/issues/2086), but it looks more like an werkzeug issue. More details may be found there as well.

when handling large file uploads +300MB, the files seem to be cached in memory till the upload is finished. This is not very practical.

To give a little more details on the code: 

```
def store_upload(project_id):
    file = request.files['file']
    # boiler plate checks ...
    file.save(os.path.join(destination_base, destination))  #save file to decent location
    return _response_stuff()
```
I am using python 3.5, flask 0.11.1., werkzeug 0.11.11

PS: I went through #pocoo and github issues here, but couldn't find any answer matching my request

PPS: also found some related issues [here](https://github.com/pallets/werkzeug/issues/510) and [here](https://github.com/codalab/codalab-cli/issues/301)

Thanks!

**UPDATE**: to better frame the issue, I made a docker image which may be tried out and illustrates the problem. See  [flask issue 2068](https://github.com/pallets/flask/issues/2086) on how to run it.

**Comment by ivarref** [comment]
Hi @cecemel I'm working on a similar issue and would just like to give the following tip: Seems gunicorn may also be a bottleneck. Saving a raw post body (no multipart/data decoding) of 1 GiB took about 10s. uwsgi uses about 4s. (And Jetty in Java uses about 1s, with multipart/data decoding.)

**Comment by cecemel** [comment]
Hi, 

thanks for the reply! 
I noticed indeed gunicorn slowed things down (and thanks for noticing uwsgi is faster, will try this asap!!) but the problem is independent of gunicorn and not really related to speed. 
If you're what into docker, you can try the docker image I made [flask issue 2068](https://github.com/pallets/flask/issues/2086). It reproduces the problem exactly.

**Comment by ivarref** [comment]
Hi @cecemel , thanks. Yeah, I know the problem is independent of gunicorn/uwsgi.

I saw the docker image. It is indeed a fine way to reproduce an issue.

PS2: I've also given the Tornado webserver a small go, and that also [takes/requires everything to be in memory](http://www.tornadoweb.org/en/stable/_modules/tornado/httputil.html#parse_multipart_form_data).

Here is the Jetty (Java) server example: https://gitlab.nsd.uib.no/ire/jetty-file-submission-performance-poc Pretty simple and fast. (But I'd rather not port my project to Java...)

**Comment by cecemel** [comment]
Hi, 
thanks for the feedback. I am also currently reluctant to port stuff to other frameworks. But, if no alternatives pop up, I'll definitively have a look again. 

Another path I am considering is using the file upload module from [nginx](https://www.nginx.com/resources/wiki/modules/upload/). I delegate the file upload there, modify the request, and pass to the flask/werkzeug service.  But has some drawbacks, such as more complexity,  no PUT request support, old module, flask code suddenly dealing with different kind of requests in different environments, potential authorization issues etc...

So, still,  a fix in flask/werkzeug (**IF** the issue is located there of course), would be awesome. Any pointers where I should look to even apply monkey patch would already be leap forward.

**Comment by ivarref** [comment]
Hi again @cecemel so I'm fairly confident that `werkzeug` is not the issue here, but `Flask`.
I've added a proof of concept project at https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc that handles 10 GB file uploads with flat memory usage (as far as I can see).

Please let me know if I'm wrong. If I'm right it would also be nice to know.

Regards

**Comment by ivarref** [comment]
I've added a sample Flask application to the same repository:
https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/blob/master/flask_app.py

At my machine it handles a 22 GiB file in ~60 seconds. Memory usage is constant at about 13 MiB.

**Comment by cecemel** [comment]
Hi, 

sorry have been caught up into other stuff. Thx for the image!
I tried it out, a docker container, and the memory problem remains the same (or almost, at first sight it seems to consume 1/3 less). [This](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/commit/a5cc4bfdc5537c1e559395b55c44de5460e5a176) commit was used.

Might it be there is a discrepancy between the docker version and the native version?

**Comment by ivarref** [comment]
Did you also use [this app](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/blob/master/flask_app.py) to handle the file uploads?

`stream,form,files = werkzeug.formparser.parse_form_data(flask.request.environ, stream_factory=custom_stream_factory)` this is the vital part to not eat up memory.

I [added printing memory usage](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/commit/6cb789b8d87eb19431ecd92ee0fcf2f520a61fcc), and after my 1,1 GiB file is submitted, memory usage is at 22 MiB.

**Comment by cecemel** [comment]
thanks again for all the assistance. 

So I retried with the same result, i.e. docker memory grows (checked docker stats with the your provided image)

> CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O               BLOCK I/O           PIDS
f057                103.71%             243.5 MiB / 2.932 GiB   8.11%               1.076 GB / 1.095 MB   3.895 MB / 0 B      1

Although the output seems to tell nothing is wrong, for 300mb post:

> saved form name file submitted as big_file to temporary file /tmp/tmpbEZOSO
handling POST request, spent 24,401 ms. 15.0 MB/s. Number of files: 1
memory usage: 19.8 MiB

Might be a docker related issue though...


PS: to run in docker, had to do some minor adaptations in your code to make [this app](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/blob/master/flask_app.py) work.

**Comment by ivarref** [comment]
Hi again.

Thanks for the `docker stats` command and feedback.

If you run Docker with `docker run --memory="100M" --publish=8090:8090 docker.nsd.no/programvareutvikling/python-file-submission-poc` you will see that the server can handle larger files than 100 MiB. So that the memory usage grows very large when not constrained is just an effect of the garbage collector not kicking in yet. I've updated [the repo](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc) with this code.

**Comment by ivarref** [comment]
For Java a sawtooth pattern of memory usage is common. http://stackoverflow.com/questions/7219532/why-a-sawtooth-shaped-graph

I'm guessing the same applies to Python.

**Comment by cecemel** [comment]
Thanks for the response! GC kicking in late, sounds like a good explanation. Sorry for addressing this issue here then.

Still, when putting the system under a certain load (behind gunicorn), in memory constrained environment, we regularly receive (just for file uploads). 
> OSError: [Errno 12] Cannot allocate memory

If you reduce the amount workers, obviously, the error is less frequent.

Last question: Do you think there is a way to better control the GC procedure as to free up memory more early during the file upload?

Issue can be closed for me.

**Comment by ivarref** [comment]
Hm. Where do you get `OSError: [Errno 12] Cannot allocate memory`? In the gunicorn app / console?

I'm not getting this (still) using [the example repo](https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/) (now slightly updated)

I've attached a screenshot for my simple test setup.
![screenshot from 2016-12-09 11-16-44](https://cloud.githubusercontent.com/assets/74075/21045588/541c7270-be01-11e6-89f6-9fbf20be6084.png)
Memory usage on my host is flat --- and at about 100 MiB for the docker container. And this handles 20 GiB files with just 100 MiB of memory. I don't see / cannot reproduce the issue you are experiencing.

Manually invoking the GC is a bad idea and should be avoided.. (It also defeats the purpose of a GC.)

**Comment by ivarref** [comment]
Does `OSError: [Errno 12] Cannot allocate memory` fail the file upload? Just curious. If so, I suppose the issue is not solved (though I'm not able to reproduce it myself).

**Comment by josauder** [comment]
Hi, I am having an issue when I try to run the Docker image, and send two large files simultaneously.

This is the code I use on the client side:

```
curl -X POST -F file=@test_1gib_file localhost:8090 & 
curl -X POST -F file=@test_1gib_file localhost:8090 & 
wait
```


When testing locally ( `gunicorn_flask.py` ) everything runs as intended.

However when I run the dockerized version, I get the following problem:

Server Side :

```
2017-07-21 14:04:35 [11] [INFO] new request
2017-07-21 14:04:35 [16] [INFO] new request
2017-07-21 14:06:34 [11] [INFO] start receiving file ... filename => /tmp/flaskappgHu3YY
2017-07-21 14:06:35 [16] [INFO] start receiving file ... filename => /tmp/flaskappd9A_cA
2017-07-21 14:06:52 [17] [INFO] Booting worker with pid: 17
2017-07-21 14:09:04 [16] [INFO] saved form name file submitted as test_1gib_file to temporary file /tmp/flaskappd9A_cA
2017-07-21 14:09:04 [16] [INFO] handling POST request, spent 268,913 ms. 3.7 MB/s. Number of files: 1
2017-07-21 14:09:04 [16] [INFO] memory usage: 73.2 MiB
2017-07-21 14:09:04 [16] [INFO] 172.17.0.1 - - [21/Jul/2017:14:09:04 +0000] "POST / HTTP/1.1" 200 12 "-" "curl/7.47.0"

```

And the curl response is

```
curl: (52) Empty reply from server
Hello World!
```

# Whats the issue?

Only one file was written to memory - the first process that reads a request and is supposed to write it to a file was killed without notice and a new worker started.

Does anybody know what the issue is? Is there any way to see more logging? I have tried adding `'loglevel': 'debug'` to the configuration but I don't get any more information.

**Comment by ivarref** [comment]
Hi. If i remeber correctly gunicorn have a timeout and if this is hit, the
worker will simply be killed.
Try to google it.

I'll unsubscribe to this issue for now...
Good luck.

**Comment by ivarref** [comment]
Oh seems that the code uses a 25 min timeout. I think default gunicorn is 5 min. I don't have good suggestion then.

**Comment by ivarref** [comment]
Could it ve that you are running out of disk space in Docker?

**Comment by davidism** [comment]
`default_stream_factory` has always stored small files in memory, dropping to a temporary file otherwise. I'm not observing any unexpected memory use here. If your temporary directory is mounted on an in-memory filesystem, you'll still see RAM usage go up, maybe that's what you observed? As shown in various examples, if you want to affect how files are stored, you can change `stream_factory`.
