### ISSUE TITLE
Deprecate `Request.is_xhr`

### ISSUE THREAD

**Issue by lepture** [pallets/werkzeug#1077]
The `Request.is_xhr` was introduced 9 years ago. It detects from a header  called `X-Requested-With` which is added by JavaScript libraries.

The world is different now. jQuery is losing its popularity; and `fetch` is shining. Many would choose to use `fetch` instead of XMLHttpRequest nowadays.  Popular ajax libraries such as axios has no built-in `X-Requested-With` header.

`X-Requested-With` is not a part of any spec, it is not reliable. It is the time to deprecate it.

**Comment by aaossa** [comment]
Hi, is this just deleting the property at [werkzeug/wrappers.py#L672](https://github.com/pallets/werkzeug/blob/760a4a95375d1d404b516fd89c2f5dd5c15cf419/werkzeug/wrappers.py#L672)? If you need a PR I could help. 

Otherwise, can you please assign me a issue to contribute to? You have 3 issues labelled "beginner friendly" (including this one, and one of them has a PR waiting for merge). Thanks!

**Comment by ThiefMaster** [comment]
just pick one of them if you want to contribute ;)

**Comment by ThiefMaster** [comment]
Deprecating the property means showing a `DeprecationWarning` - removing it would be a breaking change, i.e. something for 1.0

**Comment by aaossa** [comment]
This one is already solved by #1099 :tada:
