### ISSUE TITLE
Highlight user code in debugger

### ISSUE THREAD

**Issue by elliotwoods** [pallets/werkzeug#1165]
As discussed in :
https://github.com/pallets/flask/issues/2452 

It could be a good feature to highlight blocks relating to user's code in the call stack dump (i.e. in a `flask run` scenario in debug mode).

e.g. in the following screenshot:

![image](https://user-images.githubusercontent.com/328294/29567848-532e9866-8746-11e7-9c2b-779e588a4352.png)

The user must fix the code relating to the highlighted line. Often finding these lines takes more time than necessary. I suggest some simple improvements could be made to help, i.e. detecting files listed in `FLASK_APP`, and highlight any code lines relating to those files with a faded red background.

**Comment by tuukkamustonen** [comment]
I don't think it would be very straightforward to detect the lines that need to be highlighted:

- Highlight only line with `FLASK_APP` target in it?
- Highlight all the lines that don't contain `site-packages`?

Wouldn't supporting all the different combinations of environments (inside/outside virtualenv, develop mode, Windows/linux, etc.) be tricky?

**Comment by davidism** [comment]
I think looking for `site-packages` in the name should work for most environments. The situations I can think of where this wont work is if you do `pip install project` instead of `pip install -e project`, or on Ubuntu where the system Python uses "dist-packages". Neither should occur during development.

Should be able to loop over the frames and check the filename. Add an extra "library" class when rendering frames with "site-packages" in the filename. Style might need to be played with, but one option is to fade out all library frames unless they're hovered over.

A small heuristic for unusual envs could be to not mark anything if we end up with all user or all library frames.
