### ISSUE TITLE
Parse charset from Content-Type (if present)

### ISSUE THREAD

**Issue by srittau** [pallets/werkzeug#1214]
It would be helpful if Werkzeug would either read `Request.charset` from `environ["CONTENT_TYPE"]` (if given) or provide a help, similar to `Request.mimetype`.

Trivial implementation: `self.request.mimetype_params.get("charset", "utf-8")`.

**Comment by mitsuhiko** [comment]
@srittau that's intentionally not supported because of security reasons.

**Comment by davidism** [comment]
There is a mixin available if you want this, but you need to explicitly use it. http://werkzeug.pocoo.org/docs/0.14/contrib/wrappers/#werkzeug.contrib.wrappers.DynamicCharsetRequestMixin

@mitsuhiko what's the security issue? I'm guessing it's that Python has some "charsets" like "zlib"? https://docs.python.org/3/library/codecs.html#binary-transforms The contributed mixin docs don't warn about any security issues, so that should probably be changed.
