### ISSUE TITLE
What if default_stream_factory used a NamedTemporaryFile?

### ISSUE THREAD

**Issue by italomaia** [pallets/werkzeug#1243]
https://github.com/pallets/werkzeug/blob/8393ee88aaacf7bcd3a0b1d604511f70c222df25/werkzeug/formparser.py#L52

In the line above, if the file is big enough, a TemporaryFile is created to store it. Were it a named temporary file, activites like file size validation would be much easier, so, I would like to suggest this change.

**Comment by italomaia** [comment]
PR https://github.com/pallets/werkzeug/pull/1244

**Comment by davidism** [comment]
You can already get the size of temporary files, the same way as any open file. Use `os.stat` with `f.fileno()`.

    os.stat(f.fileno()).st_size

Apps are often deployed on services with a non-writable file system. We've already seen issues on GAE using `SpooledTemporaryFile`, not only would this run into the same thing, it may cause other issues since it actually writes an entry in the filesystem.
