### ISSUE TITLE
Could you please provide us the ECCN number for software transacation

### ISSUE THREAD

**Issue by Komalchhabra** [pallets/werkzeug#1251]

**Comment by ThiefMaster** [comment]
Sorry, but *what*?

**Comment by Komalchhabra** [comment]
We required it so that we may self-assess if there may be any prohibition or restriction for export or re-export of this product.

**Comment by ThiefMaster** [comment]
Who is "we"? And export from where to where?

Since you are asking for something that may require a significant amount of (paper-?)work on our side you may want to provide more details. A one-line issue asking for *something* doesn't seem like a great motivation for a maintainer to care about something he probably never heard about before...

**Comment by lepture** [comment]
I believe this is not an import issue for "us" (werkzeug).
