### ISSUE TITLE
0.14.2 bug fix release for status 204 Content-Length issue

### ISSUE THREAD

**Issue by ikonst** [pallets/werkzeug#1296]
Would it be possible to make a 0.14.2 bug fix release cherry-picking https://github.com/pallets/werkzeug/commit/e378a8f83d7549904abd7ae5b7ac53491a3c76cf? A few people in my organization were already impacted by this issue while upgrading their werkzeug.

Thanks!

P.S. Is this the right forum, or should I use the mailing list for this?

**Comment by weiyao21** [comment]
+1

Looking forward it! Thanks!

**Comment by Allu2** [comment]
Is there some documented reason werkzeug opts not to make releases more often?

I don't see the immediate benefit of holding fixes to bugs for next version instead of separating them from added features.  
Sure they are fixed in master, but until release is made I think majority will still keep suffering from the bugs being for all practical purposes forced to use older versions of werkzeug and missing on any improvements in the later releases until the new version is release that contains the bug fixes.

**Comment by davidism** [comment]
The next release will be 0.15, this will be in that.
