### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by KangOl** [pallets/werkzeug#131]
It would be nice to support CORS [1][2] 

even static files need to support it

[1] http://www.w3.org/TR/cors/
[2] http://enable-cors.org/

**Comment by lambdaq** [comment]
Need to bump this up.

Relative question http://stackoverflow.com/questions/19382431/set-header-on-werkzeug-exception


Related line: https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/__init__.py#L297

the `start_response('500 INTERNAL SERVER ERROR',` makes it hard to add CORS header like `Access-Control-Allow-Origin: *`. But curiously we already have `X-XSS-Protection: 0` there.

I have Flask-CORS enabled, been debugging a tricky remote ajax API call in Chrome, when Flask has an exception, I can not see the debug content because of CORS. Can we add this header in debug model?

**Comment by untitaker** [comment]
Why would you want to set a CORS header on the debug application? And why can't you do that with a wrapping middleware?

**Comment by untitaker** [comment]
Also I want to close this since I don't think we need to add every middleware to werkzeug.

**Comment by lambdaq** [comment]
@unititaker because wrapped middleware does not work at all in Werkzeug exception debugger.

Here's the "wrapping middleware" you referring to, https://github.com/corydolphin/flask-cors/issues/67

I presume @untitaker did not even take a look at the source code I linked. Here's a screenshot:

<img width="676" alt="qq20160420-3" src="https://cloud.githubusercontent.com/assets/987524/14660612/72b5a128-06d9-11e6-8fd3-720cf3d417bc.png">

**Comment by RonnyPfannschmidt** [comment]
@lambdaq now you are being mean to @untitaker 

any middleware that does wrap around a debug wrapped application can change the start_response behaviour - even for the debugger - so the code you pasted and linked seems completely irrelevant,
since a cors middle-ware wrapping around could just change it

perhaps im missing your exact problem, due to different perspective/understanding please outline  the exact use-case that seems broken/impossible

**Comment by untitaker** [comment]
The situation is made a bit tricky because the debugger middleware is applied when calling app.run. Still you can work around this by applying both your CORS and the debugger middleware manually. IMO this is fine for such an edgecase, but if you have concrete proposals for changing the debugger middleware in a way that doesn't compromise security, please do suggest them. I don't know of any easy changes though.

Also I am well aware of the code in Werkzeug. I guess that's why I'm maintaining it?

**Comment by lambdaq** [comment]
sorry, I apologize for my language, Werkzeug is awesome project. 

I guess I just have to monkey edit these `start_response()` lines and add CORS header bruteforce for my dev environment, it's more convenient than a hairy middleware.

**Comment by untitaker** [comment]
Also you might consider adding extra JS code instead that redirects to the debugger if a 500 response comes back.

**Comment by lambdaq** [comment]
@untitaker JS code can do nothing, if there's 500 error, you can only tell its http status code is 500, the traceback from the debugger page is what I am after.

also the js code is hairy compiled reactjs with tons of stuff, developed by another team, it takes 300s+ to `npm run dev`. Not easy to tweak or add few debug lines.

**Comment by pgjones** [comment]
I think #1699 resolves this. Whilst Werkzeug could do more than is in #1699, I think it should just provide accessor methods (like for cache control) and allow tools built on it (e.g. Flask-CORS or Quart-CORS) to do CORS logic.
