### ISSUE TITLE
Enable content postprocessing in Middlewares

### ISSUE THREAD

**Issue by jarkkorantala** [pallets/werkzeug#1329]
The support for [WSGI Middlewares as defined in PEP 3333](https://www.python.org/dev/peps/pep-3333/#middleware-components-that-play-both-sides) is not fully implemented. According to the WSGI spec, middlwares are meant to be able to "perform content postprocessing, such as applying XSL stylesheets". The code sample of "LatinIter" to postprocessing of a WSGI app response to pig latin does not work in Werkzeug, as the return value of start_response is ignored in `BaseResponse.__call__`.

**Comment by RonnyPfannschmidt** [comment]
as per https://www.python.org/dev/peps/pep-0333/#the-write-callable - anything new should ignore it

https://www.python.org/dev/peps/pep-0333/#middleware-components-that-play-both-sides just implements the full spec, as far as i understand right now werkzeug will just work fine with that since it doesn't use write, only the iterator interface
