### ISSUE TITLE
Better compatibility of test.Client with requests.Session

### ISSUE THREAD

**Issue by aparamon** [pallets/werkzeug#1376]
Helper class `werkzeug.test.Client` provides a useful way to unit-test Flask applications without actually running WSGI server. Oftentimes `werkzeug.test.Client` can be used as a drop-in replacement for `request.Session` in unit-test cases: it is very cool.

However, programming interfaces of `werkzeug.test.Client` and `werkzeug.wrappers.BaseResponse` are similar to but not fully compatible with `requests.Session` and `requests.Response`, respectively. It is proposed to introduce several minor changes that will increase the compatibility.

- `werkzeug.wrappers.BaseResponse` should implement property `content` similar to [requests.Response.content](http://docs.python-requests.org/en/master/api/#requests.Response.content).
- `werkzeug.wrappers.BaseResponse` should implement property `text` similar to [requests.Response.text](http://docs.python-requests.org/en/master/api/#requests.Response.text).
- `werkzeug.wrappers.BaseResponse.json` should be (`@lru_cache()`?) method, not property, similar to
[requests.Response.json()](http://docs.python-requests.org/en/master/api/#requests.Response.json). *Strictly speaking that's breaking change, but may be there is a way to keep both?*
- In addition to `get()`, `put()`, `post()`, `delete()` etc, `werkzeug.test.Client` should implement generic `request()` method, similar to [requests.Session.request](http://docs.python-requests.org/en/master/api/#requests.Session.request). Methods `get()`, `put()`, `post()`, `delete()` etc should call `request()`, which should make the actual call to `open()`: this will enable hooking/decoration of `werkzeug.test.Client.request()` compatibly with `requests.Session.request()`.

See also: https://github.com/pallets/werkzeug/issues/1258

**Comment by davidism** [comment]
I get that people like Requests, but "being like requests" is not a goal for Werkzeug. It's a coincidence that the test client API, which came well before Requests, looks like it at all. We added `json=` and have an open issue for `files=` because those are things that improve the API for common but confusing use cases.

* `content` is `r.data` or `r.get_data()`
* `text` is `r.get_data(as_text=True)`
* method is `r.get_json()`
* I don't understand the difference between this and subclassing `Client.open` to do things then call `super()...`

I thought I'd seen an extension that was adding a `Client` subclass or a Requests `TransportAdapter` subclass. A quick search found [`requests-wsgi-adapter`](https://pypi.org/project/requests-wsgi-adapter/), although I'm not sure what the status of it is.

**Comment by aparamon** [comment]
@davidism 
Thank you for your feedback!
I do see compatibility layer between `werkzeug.test.Client` and `requests.Session` as a worth goal, so I'll try to implement it as a separate project.

**Comment by davidism** [comment]
Great! I meant to suggest that in the last paragraph. I agree it's a good thing to have, it just doesn't need to be in Werkzeug itself.

One of my many todo items is to create an extensions directory on the Pallets website. When I get around to it, things like that would definitely be listed.

**Comment by aparamon** [comment]
Hi @davidism ,
And thank you for [requests-wsgi-adapter](https://pypi.org/project/requests-wsgi-adapter) link! This works like a charm so far, and is already a perfect compatibility layer supporting all the advanced Requests features like auth, plus 100%-compatible Requests API out-of-the-box.

It would definitely save me some hours and you from being needlessly bothered by me ;-) if the package was easier to discover. What's about mentioning it in http://flask.pocoo.org/docs/latest/testing ?
