### ISSUE TITLE
Request body handled incorrectly with compressed content

### ISSUE THREAD

**Issue by mistoll** [pallets/werkzeug#1437]
I'm building a REST API using Flask. The requests should support compression. The API is working fine without compression, but with compression turned on, the request data is not handled correctly.

This is my setup:

Flask-API
```
@app.route('/test', methods=['POST'])
def test():
    return jsonify({
        'headers':request.headers.to_list(),
        'body':request.data })
```

Apache2 WSGI
```
SetOutputFilter DEFLATE
AddOutputFilterByType DEFLATE application/json
SetInputFilter DEFLATE
```

The file data contains the text "Hello World". The file data.gz is the same file compressed with gzip.
Some tests:
```
# UNCOMPRESSED
> curl http://localhost:5000/test -X POST -H "Content-Type: application/json" -d @data
{
  "body": "Hello World",
  "headers": [
    [
      "Content-Length",
      "11"
    ],
    # removed Host, Accept, User-Agent
    [
      "Content-Type",
      "application/json"
    ]
  ]
}

# COMPRESSED, no Content-Length header
> curl http://localhost:5000/test -X POST -H "Content-Type: application/json" -H "Content-Length:" -H "Content-Encoding: gzip" --data-binary @data.gz
{
  "body": "", # <== EMPTY!
  "headers": [
    # removed User-Agent, Host, Accept
    [
      "Content-Encoding",
      "gzip"
    ],
    [
      "Content-Type",
      "application/json"
    ]
  ]
}

# COMPRESSED, automatic Content-Length header (curl uses Content-Length: 36)
> curl http://localhost:5000/test -X POST -H "Content-Type: application/json" -H "Content-Encoding: gzip" -d @data.gz
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>

# COMPRESSED, Content-Length header set to original data length. (compressed length)
> curl http://localhost:5000/test -X POST -H "Content-Type: application/json" -H "Content-Length: 11" -H "Content-Encoding: gzip" -d @data.gz
# Internal server error
# apache error log:
[deflate:error] AH02481: Encountered premature end-of-stream while inflating
[wsgi:error] (20014)Internal error (specific information not available): mod_wsgi (pid=11273): Unable to get bucket brigade for request.
```

I'm not sure, which content-length header is correct when using content-encoding. IMO werkzeug expects the length of the uncompressed data. However mod_deflate expects the length of the compressed data. mod_deflate can handle a missing content-length header. However werkzeug interprets a missing content-length header as content-length: 0

**Comment by davidism** [comment]
From Apache's [mod_deflate docs](https://httpd.apache.org/docs/current/mod/mod_deflate.html#input):

> **Note on Content-Length**
> 
> If you evaluate the request body yourself, *don't trust the `Content-Length` header!* The `Content-Length` header reflects the length of the incoming data from the client and *not* the byte count of the decompressed data stream.

This feels like something mod_wsgi should be handling. In example 2, Werkzeug does not deal with terminating data streams (which is what it looks like when there's no content length), so that's something the WSGI server should handle. In example 3, Werkzeug, the warning above applies, but Werkzeug has no way to know that the content length is incorrect. Example 4 isn't valid at the Apache layer.

@GrahamDumpleton any insight here? I'm not familiar with this aspect of mod_wsgi.

**Comment by GrahamDumpleton** [comment]
Werkzeug is supposed to handle this already. In mod_wsgi the WSGI value ``wsgi.input_terminated`` is set true by convention. This guarantees that the WSGI server will return an empty string as end of input marker. This means the WSGI application/framework can ignore ``CONTENT_LENGTH`` and trust that input is terminated. It therefore just reads until end of input, instead of using ``CONTENT_LENGTH``.

* https://github.com/pallets/werkzeug/blob/6aaacc6117ce8a03045e2f8aa924430f27ff5ea6/werkzeug/serving.py#L226

**Comment by GrahamDumpleton** [comment]
Whoops, probably meant:

* https://github.com/pallets/werkzeug/blob/ce162fc73ef55ca74eca237e8f5881a777a30ae4/werkzeug/wsgi.py#L222

**Comment by GrahamDumpleton** [comment]
Note that if using an ancient mod_wsgi version because you use the system mod_wsgi package provided by the Linux distro, you will not get this. You should avoid using system packages for mod_wsgi as they are usually years out of date.

**Comment by davidism** [comment]
Thanks! Since current versions of mod_wsgi support `wsgi.input_terminated`, I'm going to close this.

**Comment by mistoll** [comment]
Thanks. Solution confirmed.
After upgrade of mod_wsgi from 4.3.0 to 4.6.5:
```
> curl http://localhost:5000/test -X POST -H "Content-Type: application/json" -H "Content-Encoding: gzip" --data-binary @data.gz
{
  "body": "Hello World", 
  "headers": [
    [
      "Content-Length", 
      "36"
    ], 
    [
      "Content-Encoding", 
      "gzip"
    ], 
    [
      "Content-Type", 
      "application/json"
    ]
   # ...
  ]
}
```
