### ISSUE TITLE
PyCharm breakpoints don't work in 0.15

### ISSUE THREAD

**Issue by vinczente** [pallets/werkzeug#1493]
Hi,

It seems that using the latest version of Werkzeug disables all breakpoints while debugging a Flask app. I migrated 0.14.1 to 0.15.1 and the only change was adding the #!/usr/bin/env python to app.py.

```
/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 57061 --file app.py
pydev debugger: process 21407 is connecting

Connected to pydev debugger (build 191.6183.50)
 * Serving Flask app "application" (lazy loading)
 * Environment: DEVELOPMENT
 * Debug mode: on
INFO:werkzeug: * Running on http://0.0.0.0:8083/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 281-121-684
```

App runs without any issue and in debug mode but the breakpoints are not hit. 
Using 0.14.1 the breakpoints are hit as expected

Thanks for any feedback.

**Comment by davidism** [comment]
Please try upgrading PyCharm to the latest version.

**Comment by vinczente** [comment]
Strange, I am using the latest.

PyCharm 2019.1 (Community Edition)
Build #PC-191.6183.50, built on March 19, 2019
JRE: 11.0.2+9-b159.30 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by davidism** [comment]
Can you try creating a new virtualenv and PyCharm project?

**Comment by vinczente** [comment]
I created a test project and obviously it just works as expected :) - I will try to dig further into my setup, do you have any recommendations on what I should be looking at ?

**Comment by vinczente** [comment]
I can reproduce the issue, it seems that if app.py is executable (chmod +x) and has the shebang (#!/usr/bin/env python), the behavior occurs in 0.15.1 and not in 0.14.1, now I don't know why that is...

I was following this thread and missread some info...
https://github.com/pallets/werkzeug/issues/1482

Sorry if I made you lose time on something that shouldn't be like that in the first place

**Comment by davidism** [comment]
I'm still having trouble reproducing this. I made my example file executable and added an interpreter comment, but PyCharm's debugger still works. Can you show the run configuration you've configured in PyCharm?

**Comment by vinczente** [comment]
find attached screenshot of my run params, also the test project zip I am using

[test_werkzeug.zip](https://github.com/pallets/werkzeug/files/3023816/test_werkzeug.zip)

<img width="1183" alt="Screenshot 2019-03-29 17 32 42" src="https://user-images.githubusercontent.com/499021/55251588-db302800-5248-11e9-805e-bf031e35d00c.png">

**Comment by vinczente** [comment]
![debugg](https://user-images.githubusercontent.com/499021/55252032-c902b980-5249-11e9-9f1b-0601e0d15259.gif)

**Comment by davidism** [comment]
I can reproduce this with Python 2, it works fine with Python 3. The only thing I was thinking of was that we changed how the reloader detects what to run on reload, by checking if a file is executable. But this happens without the reloader too (debug=False). At this point I'm going to say it's an issue with PyCharm. I would have no idea how to start debugging this.

**Comment by davidism** [comment]
Never mind, I can't reproduce it with Python 2, it was just KDE's URL handler being annoying.

**Comment by davidism** [comment]
OK, I think I've tracked it down. The issue is when using the reloader with an executable file, PyCharm doesn't seem to attach to the reloaded process. #1242 and #1416 changed the reloader so that it calls executable scripts directly, but according to `ps`, "python" is still in the process name, which is what PyCharm looks for, so I'm not sure *why* it's not attaching.

**Comment by davidism** [comment]
Reported to PyCharm: https://youtrack.jetbrains.com/issue/PY-35010

To run a Flask app with PyCharm's debugger, either unmark the file as executable, or preferably use the `flask` module (or the Flask configuration if you have the Pro edition). Here's a configuration screenshot for CE, notice "module name: flask" instead of "script: ..." and the environment variables:
![image](https://user-images.githubusercontent.com/1242887/55277650-e1152000-52bf-11e9-86af-7668c9e3460b.png)
and for Pro:
![image](https://user-images.githubusercontent.com/1242887/55277688-16217280-52c0-11e9-8094-f5dd3d1b7434.png)
To run a Werkzeug app, either unmark the file as executable, or use the `werkzeug.serving` module.
![image](https://user-images.githubusercontent.com/1242887/55277846-c17ef700-52c1-11e9-882a-c1f78baee212.png)

**Comment by vinczente** [comment]
Amazing work, thanks for you help !

**Comment by Jenselme** [comment]
For your information, I ran into the same problem on a Django project. Running `chmod -x manage.py` solved the issue.
