### ISSUE TITLE
console log has improper formatting of non-ascii urls

### ISSUE THREAD

**Issue by RogerHaase** [pallets/werkzeug#1512]
With werkzeug 0.14.1, the console log for a non-ascii url (e.g. AjudaNaFormatação) looked like:

    2019-04-10 12:17:28,493 INFO werkzeug:88 127.0.0.1 - - [10/Apr/2019 12:17:28] "GET /AjudaNaFormata%C3%A7%C3%A3o HTTP/1.1" 200 -

With werkzeug 0.15.x, it now looks like:

    2019-04-10 12:13:19,315 INFO werkzeug:122 127.0.0.1 - - [10/Apr/2019 12:13:19] "GET /AjudaNaFormata+º+úo HTTP/1.1" 200 -

The problem seems to be a change to the incoming self.address_string() in serving,py near line 381:

    def log(self, type, message, *args):
        _log(type, '%s - - [%s] %s\n' % (self.address_string(),
                                         self.log_date_time_string(),
                                         message % args))

BTW, why show the date and time twice? A better format:

    2019-04-10 12:22:44,301 INFO werkzeug:88 127.0.0.1 "GET /AjudaNaFormata%C3%A7%C3%A3o HTTP/1.1" 200 -

**Comment by davidism** [comment]
This was deliberate, we want to show the unquoted URLs because it's easier for non-English devs to understand what requests the dev server is receiving. See #1115. The example shown there worked as expected in my terminal. Perhaps your terminal encoding doesn't match your Python encoding?

> why show the date and time twice?

We don't, you've done something to change Python's logger format for that logger.

**Comment by davidism** [comment]
I just tried the example you've shown, and my output looks correct.

**Comment by RogerHaase** [comment]
I was on Windows (sigh), works as you say on Ubuntu. 

Thanks for rapid response.
