### ISSUE TITLE
Binding address again on windows (SO_EXCLUSIVEADDRUSE vs SO_REUSEADDR)

### ISSUE THREAD

**Issue by Digenis** [pallets/werkzeug#1597]
On wndows, when binding an address to a socket with SO_REUSEADDR,
other sockets (from other processes too) can bind to the same address.

The reason this may be an issue is that
if someone tries unsuccessfully to kill a flask app
and the run it again to test some changes,
connections will be accepted by the old instance instead.
This can lead to looking for problems in the wrong places
(browser cache, debugging the app)

Security is also an argument
but since werkzeug is not meant for production,
I don't bring it up.

Windows provides the sensible default through SO_EXCLUSIVEADDRUSE.
Should werkzeug be using this option on it?

**Comment by davidism** [comment]
Using `SO_REUSAEADDR` here seems to be intentional based on the comments in the code. After doing some reading on these options, I'm not confident at all about making such a change right now.

If a killed process isn't actually closing, that sounds like an issue with Windows or Python, not with Werkzeug's use of sockets.
