### ISSUE TITLE
Enable x_host and x_proto by default through deprecated proxyfix?

### ISSUE THREAD

**Issue by xmo-odoo** [pallets/werkzeug#1630]
When #1314 refactored ProxyFix, it aliased num_proxies to x_for only (as that was the only one which previously supported multiple proxies).

However in doing so it disabled forwarding of host and scheme, [which were forwarded by default up to 0.14](https://github.com/pallets/werkzeug/blob/f1d15a2c7f35dcde0e52787c9fdf9ea6f6405308/werkzeug/contrib/fixers.py#L146-L151), which breaks systems relying on this.

I'd like to set x_host=1 and x_proto=1 in 0.15 IFF the user goes through the deprecated wrapper (`werkzeug.contrib.fixers.ProxyFix`) in order to restore the old behaviour, and maybe add a small warning about this behavioural change to the deprecation message (or possibly in one of the `versionchanged` blocks of the new version). Would that be acceptable / interesting or a waste of time?

**Comment by davidism** [comment]
Yeah, that sounds good.

I'm fine with adding `x_proto=1` for both, not just for the deprecated wrapper, since we think it's fairly low impact on security.

`x_host` I'm less confident about going forward, as I'm not sure what the impact is if the client can control `Host` through `X-Forwarded-Host` when Nginx isn't configured to set it. Odoo probably has a better understanding of HTTP security than I do, so if you have a good argument for leaving it enabled, I'm interested in hearing it.
