### ISSUE TITLE
_TestCookieJar.inject_wsgi doesn't take into account host information

### ISSUE THREAD

**Issue by lswainemoore** [pallets/werkzeug#1680]
Cookies have a `domain` property (https://github.com/pallets/werkzeug/blob/71cf9902012338f8ee98338fa7bba50572606637/src/werkzeug/test.py#L824), and EnvironBuilder produces an environ with `HTTPS_HOST` set based on request header values (https://github.com/pallets/werkzeug/blob/71cf9902012338f8ee98338fa7bba50572606637/src/werkzeug/test.py#L721), but in `_TestCookieJar.inject_wsgi`, all cookies are applied, independent of their domain:

`cvals = ["%s=%s" % (c.name, c.value) for c in self]` (https://github.com/pallets/werkzeug/blob/71cf9902012338f8ee98338fa7bba50572606637/src/werkzeug/test.py#L193)

Shouldn't the above list comprehension have a clause like `if c.domain.lower() == environ['HTTP_HOST'].lower()`?

**Comment by davidism** [comment]
I don't know, should it? Are you getting an error with the current behavior?

**Comment by lswainemoore** [comment]
No error. Just means that requests from two domains using the same client will share cookies, which doesn't match browser behavior.

**Comment by davidism** [comment]
Are you making requests from two domains in one test and experiencing an issue? I need some reproducible example.

**Comment by lswainemoore** [comment]
Sure, sorry. Here's a motivating example, using Flask:

views:
```
@app.route('/')
def index():
    if request.cookies.get('EXISTING_VISITOR_COOKIE'):
        return 'welcome *back* to our site'
    return 'welcome to our site'

@app.after_request
def set_cookie(response):
    response.set_cookie('EXISTING_VISITOR_COOKIE', '1', expires=....)
```

in tests:
```
def test_cookies_domain_specific(self):
    resp_a1 = self.client.get('/', headers={'Host': 'hosta.com'})
    self.assertNotIn('*back*', resp_a1.data)

    resp_a2 = self.client.get('/', headers={'Host': 'hosta.com'})
    self.assertIn('*back*', resp_a2.data)

    resp_b = self.client.get('/', headers={'Host': 'hosta.com'})
    self.assertNotIn('*back*', resp_b.data)
```

The first two asserts there will work, which is good and expected. I believe the third one will fail, which to me is unexpected, since it represents behavior different than what would occur if a browser (client) did the same sequence of requests.

**Comment by kx-chen** [comment]
Taking a look into this.

**Comment by lswainemoore** [comment]
Thanks @kx-chen! Let me know if have any difficulty reproducing the behavior or anything.

**Comment by davidism** [comment]
I think that's useful to inject the cookies based on domain and path the way the browser would. You might be testing that one subdomain set a cookie that another can see. I'm not entirely clear why `CookieJar` doesn't already do that, since it purports to behave like a browser would in terms of what cookies it accepts and sends. I think it might be that our code isn't actually _using_ `CookieJar` to set the cookies.

I don't think the rules beyond domain and path need to be handled. We're not trying to test the validation and behavior of cookies in browsers, browsers already test that. Tests avoid a using "current time", so we wouldn't handle `expires` or `max_age`. `httponly` and `samesite` don't apply. We don't really have a concept of whether a test request is `secure`. `CookieJar` also has support for stuff that isn't in the current spec, or was in a previous spec that was never implemented (`Cookie2` stuff especially). `CookieJar` already doesn't handle `__Host-` and `__Secure-` prefixes.
