### ISSUE TITLE
How to setup colorized traceback?

### ISSUE THREAD

**Issue by dufferzafar** [pallets/werkzeug#1786]
I'm using Werkzeug with a django project. Using [django_extensions' runserver_plus](https://django-extensions.readthedocs.io/en/latest/runserver_plus.html).

There are 3rd party libraries available that colorize the python tracebacks to make them a more readable. Like, https://github.com/nir0s/backtrace, https://github.com/staticshock/colored-traceback.py

I was wondering how can I integrate these tools with werkzeug? Just importing them and setting the right hooks in manage.py doesn't really work.

**Comment by davidism** [comment]
I'm sorry, I'm not familiar with those libraries. You might have better luck asking those projects, or on Stack Overflow, or our [Discord](https://discord.gg/t6rrQZH) help channel.

Flask has various error handling hooks, one of which logs the exception, so that may be a place to start if you're using Flask. If you're only using Werkzeug, your app callable probably has `try/except` to handle uncaught errors, so you'd have access to the traceback there.

The dev server and debugger use `werkzeug.debug.tbtools` to format exceptions, which provides a wrapper around Python tracebacks. If that's what's causing issues, see #1753 for first steps to working on that.
