### ISSUE TITLE
Why is this exception returning status code 200?

### ISSUE THREAD

**Issue by mmachenry** [pallets/werkzeug#1804]
I'm trying to use HTTPException to produce JSON readable bodies. It seems like HTTPException only supports HTML, so I'm implementing my own base class from HTTPException and then I suppose I need to rederive all the subclass, like Conflict here, from that. I was thinking this would work:

```
class HTTPJSONException(HTTPException):
    def __init__(self, obj):
        super().__init__(response = jsonify(obj))

    def get_headers(self, environ=None):
        return [("Content-Type", "text/json; charset=utf-8")]

class Conflict(HTTPJSONException):
    code = 409
```
It does produce a JSON body of the object I pass it properly. However, the status_code of that response is 200. What am I doing wrong?

**Comment by davidism** [comment]
Because you're overriding `response` and `jsonify` returns a response object with 200 status by default. `code` is only used when `response` is not given.

You probably want to catch `HTTPException` and return a different response from there, modifying subclasses won't do anything because those subclasses won't be raised by existing code.

Please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
