### ISSUE TITLE
send_file: allow explicit etag passing

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#1868]
`send_file` should have a kwarg for explicitly specifying an etag so it can be used even without a physical file where it would be autogenerated.

Right now one has to copy&paste code (the stuff from `if conditional:`) into their if they want to include an etag for a file that does not represent a physical file on disk, because `make_conditional` should ideally be used on a response that already has an etag set...

This depends on #1850 since it moves `send_file` from Flask to werkzeug.

**Comment by davidism** [comment]
Would allowing `add_etags` to be a string or list of strings in addition to `True` be a good idea?

**Comment by davidism** [comment]
@ThiefMaster let me know if that's what you had in mind, or something else.

**Comment by ThiefMaster** [comment]
Not sure if mixing bool and string is that clean but it certainly sounds like a solution that would work.

**Comment by kx-chen** [comment]
Will be working on this.

**Comment by davidism** [comment]
I couldn't find any reference for allowing multiple `ETag` header values, so I'm only implementing str, not list. Taking advantage of the fact that we're renaming other parameters during the move, I renamed the parameter to `etag`, since the previous name seemed incorrect on a few levels. I added a corresponding rename and warning to Flask (to got with the other two so far), although since this defaults to `True` it's unlikely to come up much.
