### ISSUE TITLE
2.0.0 Not decoding multipart-upload files with base64 encoding

### ISSUE THREAD

**Issue by Blizzke** [pallets/werkzeug#2120]
I have an API that accepts smaller json files embedded in the POST body as a form-data file

The part has the following headers:
```
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: form-data; name="configuration"; filename="configuration.json"
```
Before v2 this worked perfectly as base64 was decoded and the `FileStorage`-object I received had the correct content (the "old" FormParser.parse_lines did that I think). 
This is no longer the case. The file object contains the base64 encoded data.

Is this change in behavior intentional and did I miss something?
If so, what is the cleanest way to handle the situation please?

- Python version: 3.9
- Werkzeug version: 2.0.0

**Comment by davidism** [comment]
@pgjones looks like the multipart PR removed this. I thought we decided that was ok at the time, but I can't find that discussion.

That said, I think this was intentional. From [RFC 7578](https://datatracker.ietf.org/doc/html/rfc7578#section-4.7):

>    Previously, it was recommended that senders use a Content-Transfer-
>    Encoding encoding (such as "quoted-printable") for each non-ASCII
>    part of a multipart/form-data body because that would allow use in
>    transports that only support a "7bit" encoding.  This use is
>    deprecated for use in contexts that support binary data such as HTTP.
>    Senders SHOULD NOT generate any parts with a Content-Transfer-
>    Encoding header field.
> 
>    Currently, no deployed implementations that send such bodies have
>    been discovered.

You should send the data without extra encoding, or decode it on the server with whatever encoding you expect it to be.

**Comment by Blizzke** [comment]
Thanks for the quick reply. 

I use the `email.mime.multipart` packages to generate the body for those requests. 
I guess I'll have to take a look in there why exactly its encoding the json with base64. 
It has worked for the last +- 2 years so I've never really thought much about it.

**Comment by davidism** [comment]
Probably because it's intended for email, which has much broader rules about what's supported/required for its mime messages. While both email and http use mime, email facilities aren't actually supposed to be used for http.

**Comment by pgjones** [comment]
Yep, it was the RFC `SHOULD NOT` that convinced me to drop this support. That said I've also been asked for Quart, and it wouldn't be too painful to restore.

**Comment by davidism** [comment]
Maybe we add it back with a deprecation warning, since the RFC says it's deprecated?

It's unfortunate that `email.mime.multipart` is the only multipart encoder in the standard library, since it does things that most users of it probably don't expect. PyPA has run into this too with using it for metadata. If you can, use a higher-level library such as [httpx](https://www.python-httpx.org/) to make HTTP requests.

**Comment by Blizzke** [comment]
If I ever find myself with a couple days of "less than 20 open tickets"-time at my client, I would love to look at migrating that client library to httpx, but as it stands, it's historical and we're dragging it along :-)
In any case, I've added a wrapper around it at the API end to solve the issue for me. Feel free to close this ticket if you decide not to go ahead with adding it as deprecated, I no longer require it. Thanks again for the quick responses.

**Comment by davidism** [comment]
OK, I think I'll close it for now. If it turns out we get more feedback about it, we might revisit adding a deprecation warning.
