### ISSUE TITLE
Stat reloader CPU usage too high on Docker for Mac

### ISSUE THREAD

**Issue by martinsvoboda** [pallets/werkzeug#2141]
After migration from Werkzeug 1.0.1 to 2.0.1 stat reloader consuming 100% of CPU. I used stat reloader because inotify doesn't have good support in docker for mac. Using Werkzeug from django-extensions with runserver_plus command. Returning back to Werkzeug 1.0.1 solves problem (cpu seems ok).

Environment:

- Python version: 3.9.4
- Werkzeug version: 2.0.1
- django-extension: 3.1.3

**Comment by mgu** [comment]
It seems that the reloader generates a lot of syscalls to `stat()` for testing `isfile()`
Do you think we could cache the result of `isfile(path)` ? That would benefit to StatReloader and WatchdogReloader

**Comment by davidism** [comment]
Caching calls to `os.path.isfile()` doesn't appear to change the number of `fstatat` syscalls for either reloader. Not sure why.

**Comment by davidism** [comment]
Werkzeug 2.0 makes the stat reloader more accurate by walking all path directories, rather than only loaded module directories. This makes the stat reloader behavior match the watchdog behavior more, at the expense of higher CPU usage. I'm reluctant to undo that.

Here's some performance stats:

* If I run the reloader for an `example.py` file in the werkzeug repo directory and venv, the stat reloader watches about 300 files every 1 second, at 3.5% CPU.
* If instead I run it from somewhere very generic, such as my home directory with tons of unrelated folders and files, it is understandably much slower, watching 168388 files at 90% CPU.
* If we go back to the Werkzueg directory, but ran `tox` which created a bunch of venvs under `.tox/`, it jumps up to 8000 files, 10% CPU.

There's probably a way for you to optimize what the reloader is watching for your project in your docker container. Perhaps you copied your code to `/`, when it could be installed in a `/project/code` directory that doesn't add a very broad tree to `sys.path`. Or perhaps you have a large amount of files in the tree that can be ignored by pattern, such as `*/.tox/*`.

You can see how many paths the stat reloader is watching by running the following from the same venv and directory your project will run from:

```python
from werkzeug._reloader import _find_stat_paths
print(len(_find_stat_paths(set(), set()))
```

You can print out the list as well and perhaps identify a subtree that has files that aren't relevant to reloader and can be excluded.

You can pass a list of `fnmatch` patterns to `run_simple(..., exclude_patterns=[...])` which will tell the reloader to ignore all files matching those patterns. I'm not sure if `runserver_plus` exposes that, but `flask run` will expose that soon, or you can call `run_simple` directly for now.

The reloader already does a bit of optimization by always ignoring `__pycache__`, `.git`, and `.hg` folders. I can add some folders for common Python tools such as tox, nox, pytest, and mypy, as well as the Flask instance folder. Projects will still need to use `exclude_patterns` to tailor the list to their specific project structure.

I'm inclined to close this based on the reasoning and capabilities above, but post back about the number of files watched and if there's any exclude_patterns you can add.

**Comment by davidism** [comment]
I can do a few things to cut down on the number of files scanned by the stat reloader without meaningfully changing what is watched:

* Ignore common Python tool cache directories (tox, nox, pytest, mypy)
* Always ignore `sys.base_prefix` (it's the system Python files, not the venv, it shouldn't be changing)
* Don't recurse into any directories if they or their parent do not have any Python files (not a package or data within a package)

In the case of running from my home directory, this cuts down from 16k to 800 files. In the case of running from a project directory, it cuts down from 300 (or 8k with tox) to 150.

**Comment by martinsvoboda** [comment]
@davidism thank you for the investigation. In my case, I see the problem in https://github.com/pallets/werkzeug/blob/73ed5efd401bd3b44cfbea67bba642c681fea6b0/src/werkzeug/_reloader.py#L71

os.walk is very CPU extensive because it walks through all frontend files in the project (node_modules). Probably your third suggestion  "Don't recurse into any directories if they or their parent do not have any Python files (not a package or data within a package)" would solve the issue.

**Comment by davidism** [comment]
Node modules shouldn't be in your flask project. Separate the python and node project files.

**Comment by martinsvoboda** [comment]
It is not Flask, but Django, but it doesn't matter. Yes, there are separate, but obviously not in the way Werkzeug would expect:

```
/app/project/backend/wsgi.py
/app/project/frontend/node_modules/
/app/project/manage.py
```

Would be great if Werkzeug reloader can handle any project structure and ignore folders without Python files. Or at least document how to prevent high CPU usage. For instance, it is possible to re-mount big directories with empty docker volume:

```
volumes:
  - /var/empty:/app/project/frontend/node_modules
```
