### ISSUE TITLE
MapAdapter.build() should not flatten a value passed as single-item-list

### ISSUE THREAD

**Issue by and800** [pallets/werkzeug#2249]
Let's consider this code:

```
from flask import Flask, url_for
import logging

app = Flask(__name__)

@app.route('/test/<int:x>')
def urltest(x):
    return f"{x}"

@app.route("/")
def main():
    BUILT_URL = url_for('urltest', x=[1337])
    logging.warning(BUILT_URL)
    return ""
```

since Werkzeug v2 (apparently since b45b508c48cfca5ccbb582fdc39bbf486bed4e1a), `BUILT_URL` obtains a value `/test/1337`. But, as I understand, the call should have raised an error, because the type of parameter `x` is obviously wrong and should be `int`, not `List[int]`. If the value is a list containing single item, it is transformed to just that item. If the value contains many items, it is passed to [converter](https://github.com/pallets/werkzeug/blob/fb7ddd89ae3072e4f4002701a643eb247a402b64/src/werkzeug/routing.py#L1189) as is.

This behavior breaks my application, because I use the custom converter for lists, similar to this one: https://uniwebsidad.com/libros/explore-flask/chapter-6/url-converters#custom-converters

I don't know, maybe it is a bad idea to build URLs from a list, but this behavior feels just wrong.

Environment:

- Python version: 3.8.5
- Werkzeug version: 2.0.1

**Comment by davidism** [comment]
I don't think there's a way to change this without affecting other cases. I agree that the current behavior probably isn't correct, we shouldn't be filtering the value that would be passed to a URL converter. However, the current behavior is the result of a bunch of other user requests that were all reasonable as well. We need to talk about `MapAdapter.build`, not Flask's `url_for` wrapper around it:

* If a key is not part of the URL, it is appended as query parameters.
* If a value is `None`, it is ignored. This means URL converters will error if `None` is passed, and query parameters will not be output.
* The same key can appear multiple times for query parameters: `?a=1&a=2` is valid, and this is handled by passing a list of values for the key.
* Pairing the previous two rules, a `None` in the list of values should be ignored.
* Due to heavy optimization of the actual URL construction, we can't have much logic such as "try converting the list of values, then try converting the first item if it fails". It's *possible* to change to do this, but very difficult because we have to write the bytecode manually and don't want to affect performance too much.

All of these together currently make it difficult to pass a single item list, or a list with `None` items, to a custom converter.

**Comment by davidism** [comment]
I think #2261 is on the right track. For a `MultiDict`, continue to collapse a one-item list to that item. For a plain dict, don't collapse lists: either the user passed in a single value, or they deliberately passed a list of any length, so use that as-is

Additionally, I think we should stop filtering out `None` items from list values in plain dicts. This allows passing a list with `None` items to a custom converter. Similar this collapsing list behavior, this also carried over from the specific case of filtering a `None` value in the previous code, it was not an intended behavior.

If a user wants to pass a `MultiDict` and ensure a value remains a list with `None` items, they can add a list as the first value for a key. This is already the less common use case, so I think this slight change is fine for 2.1.
