### ISSUE TITLE
UUIDConverter should also accept strings without hyphens

### ISSUE THREAD

**Issue by tgross35** [pallets/werkzeug#2343]
It's somewhat common to have UUIDs presented without hyphens in URLs. (Pretty common for files). It would be helpful to be able to accept UUIDs at endpoints, regardless of whether or not they are hyphenated.

For cases where this is necessary, the next best possibility is to use a string type and check/create the UUID class in application code.

This is solved with a quick change in the regex:

```python
# Current
r"[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-"
r"[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}"

# New
r"[A-Fa-f0-9]{8}-?[A-Fa-f0-9]{4}-?"
r"[A-Fa-f0-9]{4}-?[A-Fa-f0-9]{4}-?[A-Fa-f0-9]{12}"
```

Python's `uuid.UUID` already accepts strings with and without hyphens (it just removes them) so nothing else would be necessary.

**Comment by davidism** [comment]
This is intentional, for the same reason that the float converter won't match "1" as "1.0".  There should not be two representations for the same URL. The converter produces URLs with "-" separators, so that's what it accepts. Caching is based on URLs and would produce different caches for the same resource. Etc.

If you need different behavior, you can add a custom converter.

```python
from werkzeug.routing import UUIDConverter

class HexUUIDConverter(UUIDConverter):
    regex = r"[A-Fa-f0-9]{32}"

    def to_url(self, value: uuid.UUID) -> str:
        return value.hex

app.url_map.converters["uuid"] = HexUUIDConverter
```
