### ISSUE TITLE
use query args for matching

### ISSUE THREAD

**Issue by alexrashed** [pallets/werkzeug#2366]
Currently, the routing framework does not allow using the query args for matching.
This is explicitly stated in the docs:
https://github.com/pallets/werkzeug/blob/eea02fb8394d66341b2ce0585b228732ef81eeea/src/werkzeug/routing.py#L1936-L1939

However, it would be really beneficial for endpoints which execute different behavior depending on a query parameter, f.e. the following two endpoints:
- `example.com/batch?mode=import`
- `example.com/batch?mode=export`

Here's an example of how I would imagine the usage could look like:
```
from urllib.request import Request
from werkzeug.exceptions import NotFound
from werkzeug.routing import Map, Rule, MapAdapter

map = Map()
map.add(Rule("/foo", endpoint="import-endpoint", query_args={"mode": "import"}))
map.add(Rule("/foo", endpoint="export-endpoint", query_args={"mode": "export"}))
map_adapter: MapAdapter = map.bind(server_name="example.com")

mapping = map_adapter.match(path_info="/batch", query_args={"mode": "import"})
assert mapping is not None
assert mapping[0] == "import-endpoint"

mapping = map_adapter.match(path_info="/batch", query_args={"mode": "export"})
assert mapping is not None
assert mapping[0] == "export-endpoint"

try:
    map_adapter.match(path_info="/batch", query_args={})
    assert False
except NotFound:
    # expected
    pass
```

In my opinion this could be done with the following changes:
- Change `MapAdapter#match` such that it gives the query args to the rule.
- Change the default rule to check the query args in `Rule#match`.

In my opinion this feature wouldn't even change the semantics of `MapAdapter#match` since it's already indicated in the current docs that the query args might be used for matching in the future. Also, additional query parameters given to `MapAdapter#match` won't have an implication since the rule matching only checks the presence of a mandatory query arg with a specific value whereas additional query args are ignored.

I'd be happy to create a PR if the takeaway of the discussion in this issue is that this feature would be a valuable addition. 😄 

PS.: Thanks for the awesome tools you provide to the world! 🥇

**Comment by alexrashed** [comment]
That would definitely be the way to go for the example I've given, if I would have the possibility to change the API. Actually I would go with a RESTy approach by using different HTTP verbs.
In my particular use case - which I derived the example from - I need to implement an API which hasn't been defined by myself (and cannot be changed at this point).

A more general example could be to implement a simple content negotiation:
- `example.com/data?format=csv`
- `example.com/data?format=json`

This could be used for integrations where you cannot influence the accept header (f.e. when sending links via mail where you want to explicitly specify the content type).

**Comment by ThiefMaster** [comment]
`example.com/data.<any(csv,json):format>`? ;)

At least to me it seems like querystring-based dispatching should be in application code. since it's rarely needed/useful and people probably should not be encouraged to add it in new projects...

**Comment by davidism** [comment]
You're welcome to subclass Map and implement this if you need it, but this is not how routing is intended to work. Routing is based on the path (and subdomain), args are distinct from the path.

**Comment by thrau** [comment]
Thanks for your input David @davidism 

> but this is not how routing is intended to work. 

It would be great if you could also let [Amazon](https://github.com/boto/botocore/blob/832e9026c75c09fa18a9e20eca3a26f3baceec09/botocore/data/apigateway/2015-07-09/service-2.json#L1445-L1449) know ;-) 

> You're welcome to subclass Map

Would you be open to a PR that adds a bit of code restructuring to make it easier to do that?

We have been looking into that for several things, but found `Map` and `MapAdapter` very difficult to extend. Since the matching logic is mostly in `Rule`, but `Rule.match` is not passed the query params, we would have to do that in `MapAdapter`. `Map.bind` needs to be completely duplicated in order to return our own implementation of `MapAdapter`, which would need a complete duplication of the entire `MapAdapter.match` logic because there are now points in the code were we could easily hook into. 

I think it would contain two things:
* moving instantiation of `MapAdapter` in `Map.bind` into a factory method of `Map`, https://github.com/pallets/werkzeug/blob/eea02fb8394d66341b2ce0585b228732ef81eeea/src/werkzeug/routing.py#L1608-L1609
* a way to hook into the `rule.match` call https://github.com/pallets/werkzeug/blob/eea02fb8394d66341b2ce0585b228732ef81eeea/src/werkzeug/routing.py#L1979
