### ISSUE TITLE
doctest causes a working out of context RuntimeError with request

### ISSUE THREAD

**Issue by alexprengere** [pallets/werkzeug#2485]
Migrating from Flask 2.1 to 2.2 failed a few unit tests of mine. It looks like we can no longer import `flask.request` top level in a test file (reproduced across Python 3.7, 3.8, 3.9, 3.10):

```python
from flask import Flask
from flask import request

def test_something():
    assert True
```

This gives a `RuntimeError`:

```
E   RuntimeError: Working outside of request context.
E
E   This typically means that you attempted to use functionality that needed
E   an active HTTP request. Consult the documentation on testing for
E   information about how to avoid this problem.
```

On my side the fix was simple: importing `flask.request` outside of the global scope, just when I actually need it (my actual tests create small Flask apps to test a client).

Edit: forgot to mention that this only occurs when pytest is run with `--doctest-modules`

**Comment by davidism** [comment]
Please provide a minimal reproducible example, including the full traceback. Avoid using pytest, just use doctest directly.

**Comment by davidism** [comment]
Running `python -m doctest example.py`, with just `from flask import request` in the file, causes the error.

What's happening is that Werkzeug only sets `__wrapped__` if the `Local` wraps a function, but does not set the attribute otherwise. Flask 2.2 started wrapping `ContextVar` directly instead of a function. Doctest uses `inspect.unwrap` to access that attribute, which fails with a proxy error instead of an attribute error. This bug was always present with doctest and previous versions, but it was hidden because of the way Flask previously used `Local`.

Unfortunately, just the presence of `__wrapped__` indicates to `inspect.unwrap` that something is a wrapper. So we can't set it to `None`, as that would make it present but incorrect.

I really think this is a bug in Python's `inspect`, it should ignore errors when accessing the attribute, but it's unlikely to get fixed there. The only think we can really do in Werkzeug is to either set the attribute to something incorrect, or see if there's a way to simulate an `AttributeError` on access.
