### ISSUE TITLE
url_encode differs from python's urllib.parse.urlencode

### ISSUE THREAD

**Issue by burkestar** [pallets/werkzeug#2513]
Why does Werkzeug have its own urlencoding methods rather than using the built-in python ones within urllib?

I noticed https://github.com/pallets/werkzeug/issues/2319 added [RFC-3986](https://www.rfc-editor.org/rfc/rfc3986#section-2
) reserved sub-delim characters such as `'` to the "always safe" list.

However, I'm not sure that's correct.

Using Python 3.7.12 and Werkzeug 2.1.2:
```
>>> from werkzeug.urls import url_encode
>>> from urllib.parse import urlencode
>>> query_args = {"some": "data with a ' character"}
>>> url_encode(query_args)
"some=data+with+a+'+character"
>>> urlencode(query_args)
'some=data+with+a+%27+character'
```

This leads to subtly different behavior.  For example, after upgrading to the newer Werkzeug our code was relying on `flask.request.full_path` to encode the query arguments consistently with urllib.parse.urlencode.

Of course, we could override this behavior with `urlencode(safe="'")` but that doesn't seem right.

See the [cpython definition of the _ALWAYS_SAFE_](https://github.com/python/cpython/blob/3.7/Lib/urllib/parse.py#L772-L777) and the docstring on the [quote method](https://github.com/python/cpython/blob/3.7/Lib/urllib/parse.py#L801-L839) which interprets the RFC.

Please forgive my cursory understanding of this RFC and the relevant areas of code if I'm missing something important.

Thanks!

**Comment by davidism** [comment]
> Why does Werkzeug have its own urlencoding methods rather than using the built-in python ones within urllib?

Because it was written in a time that the url module was less stable and also while trying to bridge the gap between Python 2 and Python 3. This is no longer needed, and I have a general long term plan to phase that out.

There is no requirement that our always safe list matches Python's. I remember looking over the RFC extensively for that PR and concluding that it was correct. I don't have the time to go through that process again now, so I'm going to leave it as-is.

**Comment by burkestar** [comment]
Ok thanks for the quick response @davidism
