### ISSUE TITLE
The existing means of obtaining docker container IDs no longer valid

### ISSUE THREAD

**Issue by mrjesen** [pallets/werkzeug#2556]
The default use of cgroups v2 in new kernels and new versions of docker makes the existing means of obtaining container IDs no longer valid

/proc/self/cgoups now  in my docker container:
```bash
root@34aafcc35eee:/proc/self# cat /proc/self/cgroup 
0::/
root@34aafcc35eee:/proc/self# 
```

**Comment by davidism** [comment]
I looked at the history of this again, and I'm not sure it really matters. The original issue report was that all Docker containers on the same host got the same pin, and that pin was "predictable". But even back then, it wasn't actually predictable, because it still included `/proc/sys/kernel/random/boot_id`, inherited from the host. The cgroup was added to make each container unique, rather than the same as the host. I'm going to just leave it as-is currently. The development server and debugger shouldn't be used in production, it shouldn't matter if each container that starts has the same debugger pin, that actually seems ideal, the pin already tries to be somewhat stable so you don't have to enter a new pin each time you start the server.

**Comment by davidism** [comment]
It's also possible to set a pin manually with `WERKZEUG_DEBUG_PIN`. If someone is concerned about having different pins per container, they can use information external to what Werkzeug can access within the container to set that env var when starting the container.
