### ISSUE TITLE
werkzeug 3.0.0 Import issue with url_quote

### ISSUE THREAD

**Issue by mababio** [pallets/werkzeug#2789]
This issue tracker is a tool to address bugs in Werkzeug itself. Please
use Pallets Discord or Stack Overflow for questions about your own code.

Getting this error message when on 3.0.0:
`ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)`
Not getting this issue with version before 3.0.0

Describe how to replicate the bug.
 Create a Dockerfile with

`FROM python
RUN pip install Flask==2.2.2
RUN pip install Werkzeug==3.0.0
RUN echo "from flask import Flask" >> app.py
CMD python app.py
`

No issue at all is the expect output

Environment:

- Python version: 3.11.5
- Werkzeug version:3.0.0

**Comment by mababio** [comment]
NVM I think this new version of werkzeug (3.0.0) is not compatible with flask 2.2.2. `url_quote` was removed from werkzeug==3.0.0 but flask==2.2.2 is referring to it.

**Comment by davidism** [comment]
You are using an unsupported version of Flask, please update to the latest version 3 if possible. 2.3 is also compatible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/

**Comment by mababio** [comment]
Thanks! This was a leaning listen

**Comment by russiantech** [comment]
> Thanks! This was a leaning listen

But if you check the urls.py, you'll notice that url_quote, url_encode & url_decode are present even in there even in the latest version of werkzeug.

**Comment by ThiefMaster** [comment]
@russiantech umm, no? https://github.com/pallets/werkzeug/blob/main/src/werkzeug/urls.py

**Comment by ThiefMaster** [comment]
My guess is that something is wrong in your environment then. `pip uninstall -y werkzeug; pip install 'werkzeug>=3'` to make sure you really have the correct version.
