### ISSUE TITLE
v3.0 "AttributeError: 'TestResponse' object has no attribute 'charset'"

### ISSUE THREAD

**Issue by jsf84ksnf** [pallets/werkzeug#2790]
When trying to load a stylesheet in a flask_weasyprint template, it fails in Werkzeug Version 3.0 with the message:
Failed to load stylesheet at http://.../static/styles/!common.css: AttributeError: 'TestResponse' object has no attribute 'charset'

After reverting to flask 2.3.3 and werkzeug 2.3.7 it the css loads again.

Environment:
- Python version: 3.11.5
- Werkzeug version: 3.0
- Flask version: 3.0
- Weasyprint version: 60.1
- flask_weasyprint version: 1.0

**Comment by davidism** [comment]
This is an expected removal, see the changelog and deprecations in the previous version.

**Comment by davidism** [comment]
When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/
