### ISSUE TITLE
Error dump_cookie in werkzeug\http.py - TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by saschapapini** [pallets/werkzeug#2795]
Hi team, with release 3.0.0 in my Flask application with Flask-sessions and SESSION_USE_SIGNER set to True on every request I receive the error

`  File "\env\Lib\site-packages\flask\app.py", line 1270, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "\env\Lib\site-packages\flask_session\sessions.py", line 164, in save_session
    response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
  File "\env\Lib\site-packages\werkzeug\sansio\response.py", line 224, in set_cookie
    dump_cookie(
  File "\env\Lib\site-packages\werkzeug\http.py", line 1303, in dump_cookie
    if not _cookie_no_quote_re.fullmatch(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object`

If I downgrade the Werkzeug version to 2.3.7 all work fine.

Environment:
- Python version: 3.11.6
- Werkzeug version: 3.0.0

**Comment by davidism** [comment]
That should be reported and fixed in Flask-Sessions if it was not already.

**Comment by davidism** [comment]
When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/
