### ISSUE TITLE
loginmanager  issue - cannot import name 'url_decode' from 'werkzeug.urls

### ISSUE THREAD

**Issue by seapoe1809** [pallets/werkzeug#2796]
This issue tracker is a tool to address bugs in Werkzeug itself. Please
use Pallets Discord or Stack Overflow for questions about your own code.

I have python 3.11 running a venv with flask 3.0 and Werkzeug 3.0. However running  from >>>flask_login import LoginManager
i get  from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/home/erver/venv/lib/python3.11/site-packages/werkzeug/urls.py)

Describe how to replicate the bug.

Include a minimal reproducible example that demonstrates the bug.
Include the full traceback if there was an exception.
I have python 3.11 running a venv with flask 3.0 and Werkzeug 3.0. However running  from >>>flask_login import LoginManager
i get  from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/home/erver/venv/lib/python3.11/site-packages/werkzeug/urls.py)

Describe the expected behavior that should have happened but didn't.
I was expecting the Loginmanager to run

Environment:

- Python version: 3.11
- Werkzeug version: 3

**Comment by ThiefMaster** [comment]
You need to wait until flask-login releases a fixed version; for not you can pin `flask<3` and `werkzeug<3`.

**Comment by davidism** [comment]
When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/
