### ISSUE TITLE
Support for partitioned cookies

### ISSUE THREAD

**Issue by alexcjohnson** [pallets/werkzeug#2797]
As part of their third-party cookie crackdown, Chrome will start requiring [partitioned cookies](https://developer.chrome.com/docs/privacy-sandbox/chips/) for content in an iframe at some point in the future. So far only [Chrome and derived browsers](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies#browser_compatibility) support this, but according to my testing other browsers accept and ignore the `Partitioned` attribute, so it should be safe to add.

My current goal is to future-proof a library that serves [Dash](https://dash.plotly.com/) apps in iframes and requires session cookies, and without built-in support the simplest solution I can find is to monkey-patch `werkzeug.sansio.response.dump_cookie` 🙈 

This functionality is effectively an extension of (and only relevant when) `SameSite=None` so I could imagine it being implemented as `samesite = "None; Partitioned"` (in the session cookie context, `app.config["SESSION_COOKIE_SAMESITE"] = "None; Partitioned"`) if you feel a separate attribute (`partitioned = True` and `app.config["SESSION_COOKIE_PARTITIONED"] = True`) would be excessive.

**Comment by davidism** [comment]
Hmm, the spec was linked pretty soon after: https://github.com/mdn/browser-compat-data/pull/20959, but the spec is described as "expired draft". This isn't really giving me confidence.

**Comment by frankier** [comment]
The specification process for this is a bit confusing as implementers have chosen different strategies:

 * Chrome has decided to implement opt-in partioning. When strict 3rd party cookies are enabled, they are blocked unless they are flagged as paritioned.
 * Firefox implements paritioned by default instead of blocking cross site cookies when strict 3rd party cookies is enabled. [They are positive on the partitioned standard](https://github.com/mozilla/standards-positions/issues/678).
 * Safari initially tried to implement a heuristic approach before giving up and blocking all 3rd party cookies. [They are also positive on the standard](https://github.com/WebKit/standards-positions/issues/50). The only modification they have suggested is a size limit, which an initial Werkzeug implementation would not need to consider.

What this means in practice is that Chrome supports the standard, and Firefox implements behaviour which interoperates with the standard by ignoring the attribute and implementing the same behavior.

I think this means this would be useful to implement already, since at this point it is very unlikely the spec will change significantly at this point. The fact the draft has expired just means that it's more than 6 months old without an update.

**Comment by wangadong** [comment]
As the phaseout of third party cookies in Chrome is approaching, we would like to implement the CHIPS aka. Partitioned cookie for some iframe usages. I would also love to see that we could support this ASAP so we don't need to hack SameSite to do this.
