### ISSUE TITLE
send_file does not include mimetype .webp images

### ISSUE THREAD

**Issue by hahhahahdnnah** [pallets/werkzeug#2835]
In modern web applications images are often displayed as .webp images. If I use `send_file` in flask the mimetype of a .webp image is not supported and therefore can not be opened in a new tab and is instant downloaded. It would be great if there is an exception for .webp images to set the mimetype to `image/webp`

1. Create a flask app
2. Make a route that sends a webp image with `send_from_directory` or `send_file`
3. Open a browser and navigate to the route that sends the webp image
4. Image get's instant downloaded

The image should be opened in a new tab but gets downloaded.

Environment:

- Python version: 3.8
- Werkzeug version: 3.0.0

**Comment by davidism** [comment]
You'll want to report that to Python, we use `mimetypes.guess_type` from the standard library.

**Comment by Ailothaen** [comment]
I had the exact same issue today while developing a website on Flask.

By going down the rabbit hole, I discovered that the type `image/webp` [was integrated](https://github.com/python/cpython/blame/3.12/Lib/mimetypes.py#L590) in the mimetypes library, but in the "non-standard" extensions list (i.e. not officially defined by IANA), so it will not be matched unless `strict=False` is passed to `mimetypes.guess_type()`.

This is still the case in Python 3.12, but will likely change soon since `image/webp` [was finally registered](https://datatracker.ietf.org/doc/draft-zern-webp/12/) in September 2023 and [a PR was issued](https://github.com/python/cpython/pull/111742) to mimetypes for that.

In the meantime, one can go around this with:
```python
import mimetypes
mimetypes.add_type("image/webp", ".webp", strict=True)
```

Modifying the code of werkzeug for it to use `strict=False` is also a possibility.
