### ISSUE TITLE
deprecate `OrderedMultiDict`

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2968]
`OrderedMultiDict` is not used by Werkzeug. It has a complex implementation, and is documented to be slow. `dict` maintains key insertion order in all supported versions of Python. `MultiDict` already maintains the insertion order of values within a key. `OrderedMultiDict` maintains the insertion order of each item, so `[(a, 1), (b, 2), (a, 3)]` comes out the same instead of `[(a, 1), (a, 3), (b, 2)]`. It's not clear there's a use case for this, searching sourcegraph shows some use of `OrderedMultiDict` but it's not clear if the use is actually required vs using `MultiDict`. Other libraries such as boltons also provide implementations. Mark this as deprecated and see if anything comes up.

**Comment by davidism** [comment]
https://sourcegraph.com/search?q=context:global+lang:Python+werkzeug+OrderedMultiDict+-file:venv+-file:site-packages+-file:werkzeug+-repo:pallets/werkzeug+&patternType=keyword&sm=0 shows ~24 repos using `OrderedMultiDict`. Browsing through them, most uses do not seem necessary.

I did see a couple cases where knowing the exact order that `request.args` or `request.form` was parsed in was important. But in that case, it's more straightforward to compare the exact data sent rather than the parsed version:

* `request.query_string` is the exact value from the URL that gets parsed into `request.args`
* `request.get_data()` called before accessing `request.form` returns the exact request body body

**Comment by davidism** [comment]
@ThiefMaster Indico uses it here: https://sourcegraph.com/github.com/indico/indico/-/blob/indico/modules/rb/api.py?L14-16, thoughts?

**Comment by ThiefMaster** [comment]
I think `parameter_storage_class = ImmutableOrderedMultiDict` (on the Request subclass) is the most interesting one, because I added that one due to how crappy the PayPal webhook validation is (they require you to send back data you received in the exact same order).

IIRC there was either something in the docs on on some SO post recommending this, so there may be more people using it when they have a paypal integration in their flask app.

The other two places where it's used are most likely leftovers from before `dict` was guaranteed to be ordered by insertion order, so if the standard MultiDict already does that now as well it's enough.

**Comment by ThiefMaster** [comment]
FWIW I don't think paypal has any multi-value keys, so probably a normal MultiDict is enough nowadays...

**Comment by davidism** [comment]
Oh yeah, that level of ordering only matters if there are actually multiple values per key, and they're submitted out of order. Seems exceedingly unlikely.
