### ISSUE TITLE
(unreleased) regression in cache-control private directive

### ISSUE THREAD

**Issue by RazerM** [pallets/werkzeug#2982]
I saw your post on Mastodon about the cache-control cleanup. Changes are looking good, `max_stale_any` will make mypy happier than the previous `int | Literal['*']` approach! :-)

I noticed a regression in the private directive and additionally I think the change entries are mixing up whether a directive is present but unqualified (without an argument) with not being present.

I have commented on the changes inline in https://github.com/pallets/werkzeug/pull/2981, since I think it's easier than copying and pasting snippets here.

Environment:

- Python version: N/A
- Werkzeug version: [main branch](https://github.com/pallets/werkzeug/pull/2981)

**Comment by davidism** [comment]
All great catches, thanks for reviewing it. I also realized when I woke up this morning that instead of breaking `max-stale` into two properties, I can type it as `int | Literal["*"] | None`, which is less disruptive to any existing uses, and type checkers still work well with that. It was currently typed as `int | str | None`, which required `isinstance` to narrow.

**Comment by davidism** [comment]
I could also use `t.Literal[True]`instead, so it would match boolean property behavior a little more.
