### ISSUE TITLE
MultiDict converts byte values to int list since version 3.1.0

### ISSUE THREAD

**Issue by ricky-provan** [pallets/werkzeug#2994]
Since version 3.1.0, when I create a MultiDict with a bytes value as input it stores the bytes value in the MultiDict as a list of integer values. Prior to 3.1.0, this would preserve the bytes value in the MultiDict.

To reproduce, run this snippet with werkzeug installed:
```python
from werkzeug.datastructures import MultiDict

multi_dict = MultiDict({
    'bytes_value': b'abc',
    'str_value': 'abc'
})

print(multi_dict)
```

Running the above on version 3.1.0 prints:
`MultiDict([('bytes_value', 97), ('bytes_value', 98), ('bytes_value', 99), ('str_value', 'abc')])`

Running the snippet with version 3.0.6 prints:
`MultiDict([('bytes_value', b'abc'), ('str_value', 'abc')])`

I expected the behaviour from 3.0.6 to be preserved in this case

Environment:
- Python version: 3.11
- Werkzeug version: >= 3.1.0

**Comment by davidism** [comment]
I switched to `isinstance(value, Collection) and not isinstance(value, str)` instead of `isinstance(value, (list, tuple))`, in order to accept more types of iterable data. However, `bytes`, `bytearray`, `memoryview`, and probably other types that shouldn't be treated as multiple values, are also matched by that. I think I might switch back to the `(list, tuple)` check.
