### ISSUE TITLE
ProxyFix should use an IP-whitelist

### ISSUE THREAD

**Issue by torotil** [pallets/werkzeug#778]
The X-Forwarded-For header usually has the following format (coming from a `proxy3`):

```
X-Forwarded-For: client, proxy1, proxy2
```

In this case there are 3 layers of reverse-proxies before the actual client IP.

Stripping a specific number of proxy-IPs from the request information seems like the easiest solution to the problem. It is also rather fragile:
- When an additional proxy-layer is used for HTTPS-offloading the number of proxies differs for HTTP and HTTPS requests.
- The only secure default for num_proxies is 0 - while the most common configuration has 1 reverse-proxy.
- Having less proxies than `num_proxies` might be a security issue.

Most web-applications that I saw up to now solved this by including a list of trusted IPs that can be stripped. This would look like:

``` python
whitelist = ['127.0.0.1', …]
forwarded_for = environ['HTTP_X_FORWARDED_FOR'].split(',')
forwarded_for.append(environ['REMOTE_ADDR'])

def get_ip(forwarded_for, whitelist):
    for ip in reversed(forwarded_for):
        if not ip in whitelist:
             return ip
    return forwarded_for[0]
```

This would allow for applications to use `whitelist = ['127.0.0.1']` as a safe default.

**Comment by davidism** [comment]
There is `werkzeug.wsgi.host_is_trusted` to correctly check a host against a whitelist, including wildcards. `Request.access_route` is a list of all values reported by `X-Forwarded-For`. If you want to do extra checks, it should be easy to build something with these.

I think the common situation is already handled securely though, adding a whitelist would induce unnecessary overhead. There's also no way to check other `X-Forwarded` headers since they don't include host information.
