### ISSUE TITLE
zombie process created with multiple workers in run_simple

### ISSUE THREAD

**Issue by mmnelemane** [pallets/werkzeug#810]
A simple server below with 2 processes creates zombie process on the server after serving a GET request. This is not observed with other server libraries (like `httpserver` with `Forkingmixin`).

~~~python
from werkzeug import serving

def application(environ, start_response):
        start_response('200 OK', [('Content-type', 'text/html')])
        return ['Hello World!!!']

serving.run_simple('127.0.0.1', 8080, application, processes=2)
~~~

Output of `ps aux | grep python` after a GET call:

~~~
user1    6824  0.1  0.0  82248 14528 pts/1    S+   09:28   0:00 python werkzeug_api.py
user1    6825  0.0  0.0      0     0 pts/1    Z+   09:28   0:00 [python] <defunct>
~~~

**Comment by mitsuhiko** [comment]
Which version of Werkzeug is this?

**Comment by mmnelemane** [comment]
This can be reproduced on "0.11.2" and "0.12-dev"

**Comment by jaapz** [comment]
@mmnelemane is there anything logged by the werkzeug server?

**Comment by mmnelemane** [comment]
Dint find any log apart from the GET calls themselves..I also tried with "use_debugger=True" option with the run_simple function. But its fairly straight forward to reproduce and check for zombie process using "top" or "ps" commands..

**Comment by aplanas** [comment]
The issue is in Python 2.7 `ForkingMinIn.collect_children`, this is collecting children when the number of active children is bigger than the number of max children (2 in this case).

We can test it in this example, checking that every time the zombie process have a different ID, meaning that the old one was properly waited (`os.waitid(-1, 0)`)

Actually I think that is more a cosmetic issue than a real issue, because eventually all the children will be collected, but can be fixed overwriting `collect_children` in the Werzeug `ForkingWSGIServer` part, iterating over all the zombie process, and updating the `active_children` list in SocketServer

**Comment by aplanas** [comment]
>  this is collecting children when the number of active children is bigger than the number of max children (2 in this case).

This is actually not the case, is collected bellow, in the `os.waitpid(pid, os.WNOHANG)`. Eventually all the Z process will be collected the next call to `process_request`

**Comment by davidism** [comment]
See https://github.com/pallets/werkzeug/pull/864#issuecomment-292814864.
