### ISSUE TITLE
Basic auth should be unicode

### ISSUE THREAD

**Issue by wosc** [pallets/werkzeug#945]
http://werkzeug.pocoo.org/docs/0.10/unicode/ says, "Werkzeug uses unicode
internally everywhere text data is assumed".

However, request.authorization.username and password are plain strings, not
unicode (see attached [basicauth_unicode.txt](https://github.com/pallets/werkzeug/files/292889/basicauth_unicode.txt)) -- which at least under Python 2 can have "interesting"
consequences, when they are interpreted according to the system encoding
(so, often utf-8), even though they are in fact latin-1 (compare
https://stackoverflow.com/a/703341).

Is this intentional? Am I missing something?

**Comment by jarek** [comment]
See also newer discussion on this topic in #1323

**Comment by davidism** [comment]
Addressed by the PR for the linked issue. Values will allow UTF-8 and be unicode in the next release.

**Comment by jarek** [comment]
Also potentially of note: in the example attached to this issue, the credentials used are `auth=(u'umläut', 'secret')` - but that is within latin1 anyway. Current version of `requests` doesn't actually support non-latin1 auth. See https://github.com/requests/requests/issues/3662 and https://github.com/requests/requests/issues/4564 for details on `requests` side. Since https://github.com/requests/requests/pull/3673, `requests` can support UTF-8 auth, but only if explicitly encoded: `auth=('имя'.encode('utf-8'), 'пароль'.encode('utf-8'))`
